# Pytorch Tutorial

## Tensors

In [ ]:
import torch

a = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]

)

a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.empty([2, 3])

tensor([[-1.6765e+29,  4.5553e-41, -1.6765e+29],
        [ 4.5553e-41,  4.4842e-44,  0.0000e+00]])

In [ ]:
torch.zeros(
    [2, 3]
)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(
    [1, 10]
)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
b = torch.tensor(
    [
        [2, 3, 4],
        [1, 2, 10]
    ]
)

torch.ones_like(b)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand([10, 2])

tensor([[0.0714, 0.3349],
        [0.8375, 0.2554],
        [0.5033, 0.0041],
        [0.0064, 0.9201],
        [0.2434, 0.2038],
        [0.8107, 0.0576],
        [0.8153, 0.1679],
        [0.0485, 0.7252],
        [0.8859, 0.5480],
        [0.1420, 0.6987]])

In [ ]:
torch.random.seed = 42

In [ ]:
 torch.randint(3, 5, (3,))

tensor([4, 4, 4])

In [ ]:
import numpy as np


numpy_array = np.array([1, 2, 3])
tensor_from_numpy = torch.from_numpy(numpy_array)

print(tensor_from_numpy)
print("="*50)
print(tensor_from_numpy.shape)

tensor([1, 2, 3])
torch.Size([3])


## Tensor Operations

In [ ]:
a = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)
b = torch.tensor(
    [
        [-1, -2, -3],
        [-4, -5, -6]
    ]
)

a + b

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
a * b

tensor([[ -1,  -4,  -9],
        [-16, -25, -36]])

In [ ]:
torch.mm(a, b.T)

tensor([[-14, -32],
        [-32, -77]])

In [ ]:
r = torch.arange(12).view(3, 4)
r

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
r.t()

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [ ]:
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')

tensor_gpu = torch.tensor([1, 2, 3]).to(device)
print(f"Tensor on device: {tensor_gpu.device}")

tensor_cpu = tensor_gpu.cpu()

Tensor on device: cpu


## Autograd

In [ ]:
import torch

x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)

z = 2 * x + 3 * y

z.backward()

print(f"x: {x}")
print(f"y: {y}")
print(f"z: {z}")
print(f"z.grad: {x.grad}")
print(f"y.grad: {y.grad}")

x: 2.0
y: 3.0
z: 13.0
z.grad: 2.0
y.grad: 3.0


In [ ]:
z.grad

/tmp/ipython-input-36-4110045842.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  z.grad


In [ ]:
x = torch.randn(3, requires_grad=True)
y = x * 2

while y.data.norm() < 1000:
  y = y * 2

print(y)

tensor([  888.6144, -1320.2974,   137.8723], grad_fn=<MulBackward0>)


In [ ]:
gradients = torch.tensor([0.1, 1.0, 0.0001])
y.backward(gradients)

print(f"Gradients of x: {x.grad}")

Gradients of x: tensor([4.0960e+02, 4.0960e+03, 4.0960e-01])


In [ ]:
t = torch.tensor(
        [1, 2, 3]
)
with torch.no_grad():
    y = t * 2
    print(f"y requires_grad: {y.requires_grad}")

y requires_grad: False


In [ ]:
z = t * 10

z_detached = z.detach()
print(f"z_datached : ", {z_detached.requires_grad})

z_datached :  {False}


In [ ]:
# Detach from computation graph
z = x * 3
z_detached = z.detach()
print(f"z_detached requires_grad: {z_detached.requires_grad}")

In [ ]:
x = torch.tensor([1., 2., 3.], requires_grad=True)
for i in range(3):
  y = x ** 2
  y.sum().backward()
  print(f"Iteration {i}: x.grad = {x.grad}")
  x.grad.zero_()  # Clear gradients

Iteration 0: x.grad = tensor([2., 4., 6.])
Iteration 1: x.grad = tensor([2., 4., 6.])
Iteration 2: x.grad = tensor([2., 4., 6.])


## Neural Network

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class SimpleNN(nn.Module):
  def __init__(self):
    super().__init__()
    self.layer1 = nn.Linear(784, 32)
    self.layer2 = nn.Linear(64, 32)
    self.layer3 = nn.Linear(32, 10)
    self.relu = nn.ReLU()
    self.softmax = nn.Softmax()

  def forward(self, x):
    x = self.relu(self.layer1(x))
    x = self.relu(self.layer2(x))
    x = self.softmax(self.layer3(x))


model = SimpleNN()
print(model)

for name, param in model.named_parameters():
  print(name, param.shape)

SimpleNN(
  (layer1): Linear(in_features=784, out_features=32, bias=True)
  (layer2): Linear(in_features=64, out_features=32, bias=True)
  (layer3): Linear(in_features=32, out_features=10, bias=True)
  (relu): ReLU()
  (softmax): Softmax(dim=None)
)
layer1.weight torch.Size([32, 784])
layer1.bias torch.Size([32])
layer2.weight torch.Size([32, 64])
layer2.bias torch.Size([32])
layer3.weight torch.Size([10, 32])
layer3.bias torch.Size([10])


## Data Loading

In [ ]:
import torch
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms


class dataset(Dataset):
  def __init__(self, data, labels, transforms=None):
    self.data = data
    self.labels = labels
    self.transform = transforms

  def __len__(self):
    return len(self.data)

  def __getitem__(self, idx):
    sample = self.data[idx]
    label = self.labels[idx]

    if self.transform:
      sample = self.transform(sample)
    return sample, label


transform = transforms.Compose(
    [
      transforms.ToPILImage(),
      transforms.RandomHorizontalFlip(),
      transforms.ToTensor(),
    ]
)

x = torch.randn((100, 3, 32, 32))
y = torch.randint(0, 10, (100,))

data = dataset(x, y, transforms=transform)

dataloader = DataLoader(data, batch_size=32, shuffle=True)

for batch_idx, (data_batch, labels_batch) in enumerate(dataloader):
  print(f"Batch {batch_idx}: Data shape {data_batch.shape}, Labels shape {labels_batch.shape}")
  break

Batch 0: Data shape torch.Size([32, 3, 32, 32]), Labels shape torch.Size([32])


In [ ]:
import torchvision
import torchvision.transforms as transforms

transform_train = transforms.Compose([
    transforms.RandomCrop(32, padding=4),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
])

transform_test = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
])

# Load CIFAR-10 dataset
trainset = torchvision.datasets.CIFAR10(
    root='./data', train=True, download=True, transform=transform_train
)
trainloader = DataLoader(trainset, batch_size=128, shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(
    root='./data', train=False, download=True, transform=transform_test
)
testloader = DataLoader(testset, batch_size=100, shuffle=False, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

100%|██████████| 170M/170M [00:02<00:00, 78.7MB/s]


In [ ]:
import torch
import torch.nn as nn
import torchvision.transforms as trasnforms
import torchvision
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset


class SimpleNN(nn.Module):
  def __init__(self, input_dim, n_class):
    super(SimpleNN, self).__init__()
    self.flat = nn.Flatten()
    self.layer1 = nn.Linear(input_dim, 256)
    self.layer2 = nn.Linear(256, 64)
    self.layer3 = nn.Linear(64, 32)
    self.layer4 = nn.Linear(32, n_class)
    self.relu = nn.ReLU()
    self.softmax = nn.Softmax()

  def forward(self, x):
    x = self.flat(x)
    x = self.relu(self.layer1(x))
    x = self.relu(self.layer2(x))
    x = self.relu(self.layer3(x))
    x = self.softmax(self.layer4(x))
    return x

model = SimpleNN(32*32*3, 10)
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=.001)
def train(model, trainloader, criterion, optimizer, num_epochs=2):
  device = 'cuda' if torch.cuda.is_available() else "cpu"
  running_loss = 0.0
  model.to(device)

  for epoch in range(num_epochs):
    for i, data in enumerate(trainloader, 0):
      inputs, labels = data[0].to(device), data[1].to(device)

      optimizer.zero_grad()
      outputs = model(inputs)
      loss = criterion(outputs, labels)
      loss.backward()
      optimizer.step()

      running_loss += loss.item()
      if i % 2000 == 1999:
          print(f'[{epoch + 1}, {i + 1:5d}] loss: {running_loss / 2000:.3f}')
          running_loss = 0.0


def test(model, testloader):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    correct = 0
    total = 0
    with torch.no_grad():
        for data in testloader:
            images, labels = data[0].to(device), data[1].to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    print(f'Accuracy of the network on the 10000 test images: {100 * correct / total:.2f}%')


train(model, trainloader, criterion, optimizer)
test(model, testloader)

Accuracy of the network on the 10000 test images: 11.22%


In [ ]:
def train_with_validation(model, train_loader, val_loader, criterion, optimizer, num_epochs=10):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    train_losses = []
    val_losses = []
    train_accuracies = []
    val_accuracies = []

    for epoch in range(num_epochs):
        model.train()
        train_loss = 0.0
        train_correct = 0
        train_total = 0

        for inputs, labels in train_loader:
            inputs, labels = inputs.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            train_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            train_total += labels.size(0)
            train_correct += (predicted == labels).sum().item()

        model.eval()
        val_loss = 0.0
        val_correct = 0
        val_total = 0

        with torch.no_grad():
            for inputs, labels in val_loader:
                inputs, labels = inputs.to(device), labels.to(device)
                outputs = model(inputs)
                loss = criterion(outputs, labels)

                val_loss += loss.item()
                _, predicted = torch.max(outputs.data, 1)
                val_total += labels.size(0)
                val_correct += (predicted == labels).sum().item()

        avg_train_loss = train_loss / len(train_loader)
        avg_val_loss = val_loss / len(val_loader)
        train_acc = 100 * train_correct / train_total
        val_acc = 100 * val_correct / val_total

        train_losses.append(avg_train_loss)
        val_losses.append(avg_val_loss)
        train_accuracies.append(train_acc)
        val_accuracies.append(val_acc)

        print(f'Epoch [{epoch+1}/{num_epochs}]')
        print(f'  Train Loss: {avg_train_loss:.4f}, Train Acc: {train_acc:.2f}%')
        print(f'  Val Loss: {avg_val_loss:.4f}, Val Acc: {val_acc:.2f}%')
        print('-' * 50)

    return train_losses, val_losses, train_accuracies, val_accuracies

train_with_validation(model, trainloader, testloader, criterion, optimizer, num_epochs=50)

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1739: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


Epoch [1/50]
  Train Loss: 2.3022, Train Acc: 10.69%
  Val Loss: 2.3022, Val Acc: 11.38%
--------------------------------------------------
Epoch [2/50]
  Train Loss: 2.3021, Train Acc: 11.04%
  Val Loss: 2.3021, Val Acc: 11.79%
--------------------------------------------------
Epoch [3/50]
  Train Loss: 2.3020, Train Acc: 11.54%
  Val Loss: 2.3020, Val Acc: 12.07%
--------------------------------------------------
Epoch [4/50]
  Train Loss: 2.3019, Train Acc: 11.78%
  Val Loss: 2.3018, Val Acc: 12.55%
--------------------------------------------------
Epoch [5/50]
  Train Loss: 2.3017, Train Acc: 12.33%
  Val Loss: 2.3017, Val Acc: 12.87%
--------------------------------------------------
Epoch [6/50]
  Train Loss: 2.3016, Train Acc: 12.60%
  Val Loss: 2.3016, Val Acc: 13.11%
--------------------------------------------------
Epoch [7/50]
  Train Loss: 2.3014, Train Acc: 13.04%
  Val Loss: 2.3015, Val Acc: 13.42%
--------------------------------------------------
Epoch [8/50]
  Train

([2.30221817560513,
  2.3020981419116944,
  2.3019693885617856,
  2.301859753211136,
  2.3017437043397324,
  2.301591561578424,
  2.301435291919562,
  2.3013082623786634,
  2.3011104408127574,
  2.3009677354027245,
  2.300770992513203,
  2.3005629390706797,
  2.300359412532328,
  2.3001275611350604,
  2.2998824034200607,
  2.29960597262663,
  2.299377230427149,
  2.2990848207107897,
  2.2987270312540975,
  2.2984187340797364,
  2.2980476011095754,
  2.2976430767332503,
  2.297254766039836,
  2.296821622897292,
  2.2963120583683025,
  2.2957416001488182,
  2.2951975630982147,
  2.294528806301029,
  2.293850182267406,
  2.2931112352844396,
  2.292337742607917,
  2.291481183922809,
  2.2905641028948147,
  2.2895064725900247,
  2.28836329269897,
  2.2872964274852783,
  2.286039404247118,
  2.28478386152126,
  2.2833919951982815,
  2.282136640890175,
  2.2807467441119806,
  2.279207253395139,
  2.2779786251390073,
  2.2764227347605672,
  2.2749798255198446,
  2.273419507019355,
  2.27146676

## Saving Model

In [ ]:
# Save the entire model
torch.save(model, 'model.pth')

# Save only the model parameters
torch.save(model.state_dict(), 'model_weights.pth')

loaded_model = torch.load('model.pth')

model = SimpleCNN()
model.load_state_dict(torch.load('model_weights.pth'))
model.eval()

## Learning Rate Scheduling

In [ ]:
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=30, gamma=0.1)

scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=100)

scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, 'min')

for epoch in range(num_epochs):
    train()
    if isinstance(scheduler, optim.lr_scheduler.ReduceLROnPlateau):
        scheduler.step(valloss)
    else:
        scheduler.step()

## Visualization

In [ ]:
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
import seaborn as sns

def plot_confusion_matrix(model, test_loader, classes):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.eval()

    all_preds = []
    all_labels = []

    with torch.no_grad():
        for inputs, labels in test_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    cm = confusion_matrix(all_labels, all_preds)
    plt.figure(figsize=(10, 8))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=classes, yticklabels=classes)
    plt.title('Confusion Matrix')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.show()

def plot_training_history(train_losses, val_losses, train_accs, val_accs):
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

    ax1.plot(train_losses, label='Train Loss')
    ax1.plot(val_losses, label='Validation Loss')
    ax1.set_title('Model Loss')
    ax1.set_xlabel('Epoch')
    ax1.set_ylabel('Loss')
    ax1.legend()

    ax2.plot(train_accs, label='Train Accuracy')
    ax2.plot(val_accs, label='Validation Accuracy')
    ax2.set_title('Model Accuracy')
    ax2.set_xlabel('Epoch')
    ax2.set_ylabel('Accuracy (%)')
    ax2.legend()

    plt.tight_layout()
    plt.show()