## Unpooling

In [6]:
from tensorflow.keras.layers import UpSampling2D
import numpy as np

In [14]:
x = np.arange(9).reshape((1, 3, 3, 1))
x

array([[[[0],
         [1],
         [2]],

        [[3],
         [4],
         [5]],

        [[6],
         [7],
         [8]]]])

In [15]:
up = UpSampling2D((2, 2))

In [17]:
result = up(x)

In [20]:
from pprint import pprint
pprint(result.numpy().reshape(-1, 6))

array([[0, 0, 1, 1, 2, 2],
       [0, 0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5, 5],
       [3, 3, 4, 4, 5, 5],
       [6, 6, 7, 7, 8, 8],
       [6, 6, 7, 7, 8, 8]])


In [27]:
from tensorflow.keras.layers import Conv2DTranspose

layer = Conv2DTranspose(1, (2, 2))

In [28]:
layer(x.astype(float))

<tf.Tensor: shape=(1, 4, 4, 1), dtype=float32, numpy=
array([[[[ 0.        ],
         [ 0.36314398],
         [ 1.4774332 ],
         [ 1.5022904 ]],

        [[ 1.089432  ],
         [ 3.61055   ],
         [ 3.9622684 ],
         [ 2.4215078 ]],

        [[ 1.8924794 ],
         [ 4.665706  ],
         [ 5.017424  ],
         [ 2.6736164 ]],

        [[-0.5727693 ],
         [-4.670885  ],
         [-5.4334555 ],
         [-5.336872  ]]]], dtype=float32)>